name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    env:
      # Add all required environment variables here
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
      # Add any other required environment variables

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Configure Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: './yarn.lock'
          corepack: true
          
      - name: Enable Corepack
        run: corepack enable
          
      - name: Install dependencies
        run: yarn install
        
      - name: Verify TypeScript compilation
        run: yarn workspace frontend run typecheck
        
      - name: Check code quality
        run: yarn workspace frontend run lint
        
      - name: Create production build
        run: yarn workspace frontend run build

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Configure Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: './yarn.lock'
          corepack: true
          
      - name: Enable Corepack
        run: corepack enable
          
      - name: Install dependencies
        run: yarn install
        
      - name: Verify TypeScript compilation
        run: yarn workspace backend run typecheck
        
      - name: Check code quality
        run: yarn workspace backend run lint
        
      - name: Create production build
        run: yarn workspace backend run build