name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend  # Adjust this path to match your frontend directory

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: './frontend/yarn.lock'
          
      - name: Install dependencies
        run: yarn install
        
      - name: Type check
        run: yarn type-check
        
      - name: Lint
        run: yarn lint
        
      - name: Build
        run: yarn build

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend  # Adjust this path to match your backend directory

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: './backend/yarn.lock'
          
      - name: Install dependencies
        run: yarn install
        
      - name: Type check
        run: yarn type-check
        
      - name: Lint
        run: yarn lint
        
      - name: Build
        run: yarn build